In [69]:
import numpy as np
import pandas as pd

In [70]:
class K_mean:
  def __init__(self,K,maxiter):
    self.K = K
    # Định nghĩa số vòng lặp tối đa cho phép
    self.maxiter = maxiter
  def fit(self,X):
    self.X = X
    self.new_centroids = self.X[np.random.choice(self.X.shape[0],self.K,replace=False)]
    matrix_distance = np.stack((np.zeros((self.X.shape[0],1)),)*self.K,axis = 2)
    print(self.new_centroids)
    print('-------')
    self.old_centroids = np.zeros(self.new_centroids.shape)
    while not np.allclose(self.new_centroids,self.old_centroids) and self.maxiter > 0:
      for i in range(self.K):
        matrix_distance[:,:,i] = np.sqrt(((self.new_centroids[i].reshape(1,-1) - self.X)**2).sum(axis = 1)).reshape(self.X.shape[0],-1)
      matrix_clusterings = np.argmin(matrix_distance,axis=2)
      # Chỗ này không được gán trực tiếp hai mảng bằng nhau => mảng được gán sẽ trỏ đến vùng nhớ với mảng gán
      self.old_centroids = self.new_centroids.copy()
      for i in range(self.K):
        self.new_centroids[i] = np.mean(self.X[matrix_clusterings ==i],axis=0)
      print(f"old_centroids = {self.old_centroids}")
      print("--------")
      print(f"new_centroids = {self.new_centroids}")
      print('--------')
      print(not np.allclose(self.new_centroids,self.old_centroids))
      self.maxiter-=1
      self.Label = matrix_clusterings

In [76]:
K_mean_clustering = K_mean(K=2,maxiter=100)

In [77]:
X = np.array([1.4,1,1.5,3.1,3.8,4.1]).reshape(-1,1)

In [78]:
K_mean_clustering.fit(X)

[[3.1]
 [4.1]]
-------
old_centroids = [[3.1]
 [4.1]]
--------
new_centroids = [[1.75]
 [3.95]]
--------
True
old_centroids = [[1.75]
 [3.95]]
--------
new_centroids = [[1.3       ]
 [3.66666667]]
--------
True
old_centroids = [[1.3       ]
 [3.66666667]]
--------
new_centroids = [[1.3       ]
 [3.66666667]]
--------
False


In [79]:
K_mean_clustering.Label

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1]])

In [81]:
a = np.arange(12).reshape(6,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [9]:
a[np.newaxis,:,:]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [10]:
b = np.array([
    [0, 1],\
    [2, 3]
])
b

array([[0, 1],
       [2, 3]])

In [11]:
b[:,np.newaxis,:]

array([[[0, 1]],

       [[2, 3]]])

In [12]:
a[np.newaxis,:,:] - b[:,np.newaxis,:]

array([[[ 0,  0],
        [ 2,  2],
        [ 4,  4],
        [ 6,  6],
        [ 8,  8],
        [10, 10]],

       [[-2, -2],
        [ 0,  0],
        [ 2,  2],
        [ 4,  4],
        [ 6,  6],
        [ 8,  8]]])

In [ ]:
(a[np.newaxis,:,:] - b[:,np.newaxis,:]).sum(axis=0)

array([[-2, -2],
       [ 2,  2],
       [ 6,  6],
       [10, 10],
       [14, 14],
       [18, 18]])

In [ ]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
b

array([[0, 1],
       [2, 3]])

In [ ]:
a[:,np.newaxis,:]

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]]])

In [ ]:
a[:,np.newaxis,:] - b

array([[[ 0,  0],
        [-2, -2]],

       [[ 2,  2],
        [ 0,  0]],

       [[ 4,  4],
        [ 2,  2]],

       [[ 6,  6],
        [ 4,  4]],

       [[ 8,  8],
        [ 6,  6]],

       [[10, 10],
        [ 8,  8]]])

In [ ]:
np.array([[[ 0,  1],
           [ 0,  1]],

       [[ 2,  3],
        [ 2,  3]],

       [[ 4,  5],
        [ 4,  5]],

       [[ 6,  7],
        [ 6,  7]],

       [[ 8,  9],
        [ 8,  9]],

       [[10, 11],
        [10, 11]]])

array([[[ 0,  1],
        [ 0,  1]],

       [[ 2,  3],
        [ 2,  3]],

       [[ 4,  5],
        [ 4,  5]],

       [[ 6,  7],
        [ 6,  7]],

       [[ 8,  9],
        [ 8,  9]],

       [[10, 11],
        [10, 11]]])

In [ ]:
(a[:,np.newaxis,:] - b)**2

array([[[  0,   0],
        [  4,   4]],

       [[  4,   4],
        [  0,   0]],

       [[ 16,  16],
        [  4,   4]],

       [[ 36,  36],
        [ 16,  16]],

       [[ 64,  64],
        [ 36,  36]],

       [[100, 100],
        [ 64,  64]]])